set(_CATKIN_CURRENT_PACKAGE "mbzirc_gcs_core")
set(mbzirc_gcs_core_VERSION "0.0.0")
set(mbzirc_gcs_core_MAINTAINER "luisgrvc <luisgrvc@todo.todo>")
set(mbzirc_gcs_core_PACKAGE_FORMAT "1")
set(mbzirc_gcs_core_BUILD_DEPENDS "grvc_quadrotor_com" "grvc_quadrotor_hal" "grvc_quadrotor_uav" "roscpp" "std_msgs")
set(mbzirc_gcs_core_BUILD_EXPORT_DEPENDS "grvc_quadrotor_com" "grvc_quadrotor_hal" "grvc_quadrotor_uav" "roscpp" "std_msgs")
set(mbzirc_gcs_core_BUILDTOOL_DEPENDS "catkin")
set(mbzirc_gcs_core_BUILDTOOL_EXPORT_DEPENDS )
set(mbzirc_gcs_core_EXEC_DEPENDS "grvc_quadrotor_com" "grvc_quadrotor_hal" "grvc_quadrotor_uav" "roscpp" "std_msgs")
set(mbzirc_gcs_core_RUN_DEPENDS "grvc_quadrotor_com" "grvc_quadrotor_hal" "grvc_quadrotor_uav" "roscpp" "std_msgs")
set(mbzirc_gcs_core_TEST_DEPENDS )
set(mbzirc_gcs_core_DOC_DEPENDS )
set(mbzirc_gcs_core_DEPRECATED "")