#!/bin/bash
# This scripts launches all in UAV 3 

roslaunch mbzirc_launchers core_real_3.launch

sleep 5

roslaunch mbzirc_launchers hal_real_3.launch

sleep 5

./vision_node ../cfg/vision/realData_3.xml


