set(_CATKIN_CURRENT_PACKAGE "offboard")
set(offboard_VERSION "0.0.0")
set(offboard_MAINTAINER "mbzhiz <mbzhiz@todo.todo>")
set(offboard_PACKAGE_FORMAT "1")
set(offboard_BUILD_DEPENDS "geometry_msgs" "mavros" "mavros_msgs" "roscpp")
set(offboard_BUILD_EXPORT_DEPENDS "geometry_msgs" "mavros" "mavros_msgs" "roscpp")
set(offboard_BUILDTOOL_DEPENDS "catkin")
set(offboard_BUILDTOOL_EXPORT_DEPENDS )
set(offboard_EXEC_DEPENDS "geometry_msgs" "mavros" "mavros_msgs" "roscpp")
set(offboard_RUN_DEPENDS "geometry_msgs" "mavros" "mavros_msgs" "roscpp")
set(offboard_TEST_DEPENDS )
set(offboard_DOC_DEPENDS )
set(offboard_DEPRECATED "")