set(_CATKIN_CURRENT_PACKAGE "mbzirc_quick_mission")
set(mbzirc_quick_mission_VERSION "0.0.0")
set(mbzirc_quick_mission_MAINTAINER "luisgrvc <luisgrvc@todo.todo>")
set(mbzirc_quick_mission_PACKAGE_FORMAT "1")
set(mbzirc_quick_mission_BUILD_DEPENDS "grvc_quadrotor_uav" "grvc_quadrotor_utils" "mbzirc_gcs_core")
set(mbzirc_quick_mission_BUILD_EXPORT_DEPENDS "grvc_quadrotor_uav" "grvc_quadrotor_utils" "mbzirc_gcs_core")
set(mbzirc_quick_mission_BUILDTOOL_DEPENDS "catkin")
set(mbzirc_quick_mission_BUILDTOOL_EXPORT_DEPENDS )
set(mbzirc_quick_mission_EXEC_DEPENDS "grvc_quadrotor_uav" "grvc_quadrotor_utils" "mbzirc_gcs_core")
set(mbzirc_quick_mission_RUN_DEPENDS "grvc_quadrotor_uav" "grvc_quadrotor_utils" "mbzirc_gcs_core")
set(mbzirc_quick_mission_TEST_DEPENDS )
set(mbzirc_quick_mission_DOC_DEPENDS )
set(mbzirc_quick_mission_DEPRECATED "")