set(_CATKIN_CURRENT_PACKAGE "mbzirc_qt_gcs")
set(mbzirc_qt_gcs_VERSION "0.0.0")
set(mbzirc_qt_gcs_MAINTAINER "prs <prs@us.es>")
set(mbzirc_qt_gcs_PACKAGE_FORMAT "1")
set(mbzirc_qt_gcs_BUILD_DEPENDS "grvc_quadrotor_uav" "grvc_quadrotor_utils" "mbzirc_gcs_core" "uav_visual_servoing")
set(mbzirc_qt_gcs_BUILD_EXPORT_DEPENDS "uav_visual_servoing" "grvc_quadrotor_uav" "grvc_quadrotor_utils" "mbzirc_gcs_core")
set(mbzirc_qt_gcs_BUILDTOOL_DEPENDS "catkin")
set(mbzirc_qt_gcs_BUILDTOOL_EXPORT_DEPENDS )
set(mbzirc_qt_gcs_EXEC_DEPENDS "uav_visual_servoing" "grvc_quadrotor_uav" "grvc_quadrotor_utils" "mbzirc_gcs_core")
set(mbzirc_qt_gcs_RUN_DEPENDS "uav_visual_servoing" "grvc_quadrotor_uav" "grvc_quadrotor_utils" "mbzirc_gcs_core")
set(mbzirc_qt_gcs_TEST_DEPENDS )
set(mbzirc_qt_gcs_DOC_DEPENDS )
set(mbzirc_qt_gcs_DEPRECATED "")