set(_CATKIN_CURRENT_PACKAGE "mbzirc_gcs_view")
set(mbzirc_gcs_view_VERSION "0.0.0")
set(mbzirc_gcs_view_MAINTAINER "luisgrvc <luisgrvc@todo.todo>")
set(mbzirc_gcs_view_PACKAGE_FORMAT "1")
set(mbzirc_gcs_view_BUILD_DEPENDS "grvc_quadrotor_com" "roscpp" "sensor_msgs" "image_transport" "std_msgs" "cv_bridge" "opencv2" "grvc_quadrotor_hal")
set(mbzirc_gcs_view_BUILD_EXPORT_DEPENDS "grvc_quadrotor_com" "grvc_quadrotor_hal" "roscpp" "sensor_msgs" "image_transport" "std_msgs" "cv_bridge" "opencv2" "hector_sensors_description")
set(mbzirc_gcs_view_BUILDTOOL_DEPENDS "catkin")
set(mbzirc_gcs_view_BUILDTOOL_EXPORT_DEPENDS )
set(mbzirc_gcs_view_EXEC_DEPENDS "grvc_quadrotor_com" "grvc_quadrotor_hal" "roscpp" "sensor_msgs" "image_transport" "std_msgs" "cv_bridge" "opencv2" "hector_sensors_description")
set(mbzirc_gcs_view_RUN_DEPENDS "grvc_quadrotor_com" "grvc_quadrotor_hal" "roscpp" "sensor_msgs" "image_transport" "std_msgs" "cv_bridge" "opencv2" "hector_sensors_description")
set(mbzirc_gcs_view_TEST_DEPENDS )
set(mbzirc_gcs_view_DOC_DEPENDS )
set(mbzirc_gcs_view_DEPRECATED "")